name: Trigger auto deployment for payvenlivedemo9190b572

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/payvenlivedemo9190b572-AutoDeployTrigger-37555d78-d1f0-430e-98a4-57184f470631.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PAYVENLIVEDEMO9190B572_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PAYVENLIVEDEMO9190B572_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PAYVENLIVEDEMO9190B572_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.PAYVENLIVEDEMO9190B572_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PAYVENLIVEDEMO9190B572_REGISTRY_PASSWORD }}
          containerAppName: payvenlivedemo9190b572
          resourceGroup: payvenlivedemo9190
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


